"""Initial Supabase schema

Revision ID: 0f6538b84133
Revises: 
Create Date: 2026-08-09 22:55:09.716607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


# revision identifiers, used by Alembic.
revision: str = '0f6538b84133'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_messages', 'retrieved_chunk_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('idx_chat_messages_session_id'), table_name='chat_messages')
    op.alter_column('chat_sessions', 'material_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_chat_sessions_material_id'), table_name='chat_sessions')
    op.drop_index(op.f('idx_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_constraint(op.f('chat_sessions_material_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'materials', ['material_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_material_chunks_material_id'), table_name='material_chunks')
    op.drop_constraint(op.f('material_chunks_material_id_chunk_index_key'), 'material_chunks', type_='unique')
    op.alter_column('material_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=True)
    op.drop_index(op.f('idx_embeddings_chunk_id'), table_name='material_embeddings')
    op.drop_index(op.f('idx_embeddings_material_id'), table_name='material_embeddings')
    op.drop_index(op.f('idx_embeddings_vector'), table_name='material_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('materials', 'source_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('materials', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('materials', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('materials', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('materials', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('materials', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('materials', 'vector_store_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('materials', 'title_normalized',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.Computed('normalize_arabic(lower(title))', persisted=True))
    op.drop_index(op.f('idx_materials_status'), table_name='materials')
    op.drop_index(op.f('idx_materials_title_normalized_trgm'), table_name='materials', postgresql_using='gin')
    op.drop_index(op.f('idx_materials_title_trgm'), table_name='materials', postgresql_using='gin')
    op.drop_index(op.f('idx_materials_user_id'), table_name='materials')
    op.drop_constraint(op.f('materials_user_id_title_key'), 'materials', type_='unique')
    op.alter_column('profiles', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('profiles', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('profiles', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('profiles', 'last_request_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('profiles', 'theme',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::text"))
    op.drop_constraint(op.f('profiles_id_fkey'), 'profiles', type_='foreignkey')
    op.alter_column('quiz_attempts', 'score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quiz_attempts', 'total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quiz_attempts', 'results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('idx_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.alter_column('quizzes', 'source_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('quizzes', 'difficulty',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('quizzes', 'mcq_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quizzes', 'tf_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quizzes', 'quiz_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('quizzes', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'completed'::text"))
    op.alter_column('quizzes', 'model_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('quizzes', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_quizzes_material_id'), table_name='quizzes')
    op.drop_index(op.f('idx_quizzes_user_id'), table_name='quizzes')
    op.drop_constraint(op.f('quizzes_material_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'materials', ['material_id'], ['id'], ondelete='CASCADE')
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('idx_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.alter_column('summaries', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'completed'::text"))
    op.alter_column('summaries', 'model_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('summaries', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_summaries_material_id'), table_name='summaries')
    op.drop_constraint(op.f('summaries_material_id_key'), 'summaries', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('summaries_material_id_key'), 'summaries', ['material_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_summaries_material_id'), 'summaries', ['material_id'], unique=False)
    op.alter_column('summaries', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('summaries', 'model_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('summaries', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'completed'::text"))
    op.create_index(op.f('idx_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_material_id_fkey'), 'quizzes', 'materials', ['material_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_quizzes_user_id'), 'quizzes', ['user_id'], unique=False)
    op.create_index(op.f('idx_quizzes_material_id'), 'quizzes', ['material_id'], unique=False)
    op.alter_column('quizzes', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('quizzes', 'model_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('quizzes', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'completed'::text"))
    op.alter_column('quizzes', 'quiz_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('quizzes', 'tf_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quizzes', 'mcq_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quizzes', 'difficulty',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('quizzes', 'source_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('idx_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.alter_column('quiz_attempts', 'results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('quiz_attempts', 'total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quiz_attempts', 'score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(op.f('profiles_id_fkey'), 'profiles', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
    op.alter_column('profiles', 'theme',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'system'::text"))
    op.alter_column('profiles', 'last_request_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('profiles', 'avatar_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'display_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_unique_constraint(op.f('materials_user_id_title_key'), 'materials', ['user_id', 'title'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_materials_user_id'), 'materials', ['user_id'], unique=False)
    op.create_index(op.f('idx_materials_title_trgm'), 'materials', ['title'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_materials_title_normalized_trgm'), 'materials', ['title_normalized'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_materials_status'), 'materials', ['status'], unique=False)
    op.alter_column('materials', 'title_normalized',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.Computed('normalize_arabic(lower(title))', persisted=True))
    op.alter_column('materials', 'vector_store_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('materials', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('materials', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('materials', 'url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('materials', 'file_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('materials', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('materials', 'source_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_embeddings_vector'), 'material_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('idx_embeddings_material_id'), 'material_embeddings', ['material_id'], unique=False)
    op.create_index(op.f('idx_embeddings_chunk_id'), 'material_embeddings', ['chunk_id'], unique=False)
    op.alter_column('material_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=False)
    op.create_unique_constraint(op.f('material_chunks_material_id_chunk_index_key'), 'material_chunks', ['material_id', 'chunk_index'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_material_chunks_material_id'), 'material_chunks', ['material_id'], unique=False)
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_material_id_fkey'), 'chat_sessions', 'materials', ['material_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_chat_sessions_material_id'), 'chat_sessions', ['material_id'], unique=False)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chat_sessions', 'material_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('chat_messages', 'retrieved_chunk_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.UUID()),
               existing_nullable=True)
    op.alter_column('chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
